name: InventoryCommands
version: '${version}'

main: ic.dxvampi.inventoryCommands.InventoryCommands
paperPluginLoader: ic.dxvampi.inventoryCommands.InventoryCommandsLoader
api-version: '1.18'
load: POSTWORLD
